### ISSUE TITLE
The link of resnet18_cifar10.model is fail 

### ISSUE THREAD

**Issue by kkk324** [passalis/probabilistic_kt#1]
Hi Passalis,

 The link of resnet18_cifar10.model is fail and also the lack of model in exp_cifar/models. 

CR

**Comment by passalis** [comment]
The file was accidentally deleted while I was updating the repository files with the Youtube Faces dataset. I restored the file, so you should be able to download and use it from https://www.dropbox.com/s/6jvhn3pjedqika1/resnet18_cifar10.model?dl=0

You can also directly re-trained the teacher model (if you want to do so).

**Comment by kkk324** [comment]
Thanks for the quick reply. 
Both download link and re-trained model are work!

**Comment by passalis** [comment]
Thank you for finding the broken link and providing feedback!
