### ISSUE TITLE
'cosine_similarity_loss' function

### ISSUE THREAD

**Issue by Jubi-Hwang** [passalis/probabilistic_kt#2]
Hello. I have a question about your code implementation of 'cosine_similarity_loss'.

**output_net[output_net != output_net] = 0**
and
**target_net[target_net != target_net] = 0**

Can you explain to me why those codes were written?
Does the function have the same results without above two code lines?

Thank you for considering my question.

**Comment by passalis** [comment]
Hi @Jubi-Hwang 

If I recall correctly, I think this was a hack to easily remove NaNs back then before `isnan()` was introduced in PyTorch.

**Comment by Jubi-Hwang** [comment]
@passalis Oh, thank you for your answer.
